### ISSUE TITLE
Added repo and dependency to gradle. Artifact not found.

### ISSUE THREAD

**Issue by muksihs** [RHazDev/Java-IPFS-Daemon#1]
Added repo and dependency to gradle. Artifact not found.

So I tried via jitpack and the build fails: Could not find artifact fr.rhaz:events:jar

INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.657 s
[INFO] Finished at: 2018-10-03T22:34:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project daemon: Could not resolve dependencies for project fr.rhaz.ipfs:daemon:jar:1.1: Could not find artifact fr.rhaz:events:jar:1.0 in jitpack.io (https://jitpack.io) -> [Help 1]

**Comment by Hazae41** [comment]
The new version is here https://github.com/RHazDev/IPFS-Daemon
forgot to add it to the readme
